### ISSUE TITLE
请问可以打包成exe，然后在界面里面选择blh模型吗，那实用性会打打提高

### ISSUE THREAD

**Issue by Miki-lin** [LSH9832/SAMLabelerPro#1]
请问可以打包成exe，然后在界面里面选择blh模型吗，那实用性会打打提高

**Comment by LSH9832** [comment]
不同显卡支持的CUDA版本不一定相同，我打包后的不一定兼容你的电脑。界面选择模型这个做起来不难，后续会考虑加上，如果着急可以自己改，就是加几行代码的事儿

**Comment by Miki-lin** [comment]
我解决了，谢谢你！
